# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('createDate', models.DateTimeField(default=datetime.datetime(2016, 4, 25, 23, 11, 25, 835055))),
                ('rating', models.IntegerField(default=0)),
                ('genres', models.ManyToManyField(to='music.Genre')),
            ],
        ),
    ]
