# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='track',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 10, 12, 45, 152003)),
        ),
    ]
