# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20160426_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 11, 43, 24, 918185)),
        ),
    ]
